name: AutoMendingmachine
version: ${project.version}
main: mametaku.automendingmachine.AutoMendingmachine
api-version: 1.16
commands:
  amm:
    description: give machine
    usage: /<command>
    default: op